name: CD

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install FN project
      run: curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      
    - name: Install Docker
      run: |
        sudo apt update
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
        sudo apt update
        sudo apt install docker-ce
        
    - name: Setup FN project
      env:
        ORACLE_COMPARTMENT: ${{ secrets.ORACLE_COMPARTMENT }}
        ORACLE_API: ${{ secrets.ORACLE_API }}
        ORACLE_REGISTRY: ${{ secrets.ORACLE_REGISTRY }}
        ORACLE_DOCKER_USER: ${{ secrets.ORACLE_DOCKER_USER }}
        ORACLE_DOCKER_PASS: ${{ secrets.ORACLE_DOCKER_PASS }}
      run: |
        fn create context smartprograms-root --provider oracle
        fn use context smartprograms-root
        fn update context oracle.compartment-id $ORACLE_COMPARTMENT
        fn update context api-url $ORACLE_API
        fn update context registry phx.ocir.io/axdoipz9dgju/$ORACLE_REGISTRY
        docker login phx.ocir.io --username $ORACLE_DOCKER_USER --password $ORACLE_DOCKER_PASS
        
    - name: Create Config File
      run: |
        mkdir $HOME/.oci
        echo "${{secrets.ORACLE_CONFIG}}" >> $HOME/.oci/config
    
    - name: Create Key File
      run: |
        echo "${{secrets.ORACLE_KEY_FILE}}" >> $HOME/.oci/oci_api_key.pem
        ls $HOME/.oci/
        
    - name: Deploy
      run: DEBUG=1 fn deploy --app smartclips
